// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: example.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GreetPersonRequest has string parameters
type GreetPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetPersonRequest) Reset() {
	*x = GreetPersonRequest{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetPersonRequest) ProtoMessage() {}

func (x *GreetPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetPersonRequest.ProtoReflect.Descriptor instead.
func (*GreetPersonRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *GreetPersonRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GreetPersonRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

// GreetPersonResponse returns a string
type GreetPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetPersonResponse) Reset() {
	*x = GreetPersonResponse{}
	mi := &file_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetPersonResponse) ProtoMessage() {}

func (x *GreetPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetPersonResponse.ProtoReflect.Descriptor instead.
func (*GreetPersonResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *GreetPersonResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

// CalculateSumRequest has numeric parameters
type CalculateSumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number1       int32                  `protobuf:"varint,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2       int32                  `protobuf:"varint,2,opt,name=number2,proto3" json:"number2,omitempty"`
	Factor        float64                `protobuf:"fixed64,3,opt,name=factor,proto3" json:"factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateSumRequest) Reset() {
	*x = CalculateSumRequest{}
	mi := &file_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateSumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSumRequest) ProtoMessage() {}

func (x *CalculateSumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSumRequest.ProtoReflect.Descriptor instead.
func (*CalculateSumRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateSumRequest) GetNumber1() int32 {
	if x != nil {
		return x.Number1
	}
	return 0
}

func (x *CalculateSumRequest) GetNumber2() int32 {
	if x != nil {
		return x.Number2
	}
	return 0
}

func (x *CalculateSumRequest) GetFactor() float64 {
	if x != nil {
		return x.Factor
	}
	return 0
}

// CalculateSumResponse returns numeric results
type CalculateSumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int32                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Product       float64                `protobuf:"fixed64,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateSumResponse) Reset() {
	*x = CalculateSumResponse{}
	mi := &file_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateSumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSumResponse) ProtoMessage() {}

func (x *CalculateSumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSumResponse.ProtoReflect.Descriptor instead.
func (*CalculateSumResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateSumResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *CalculateSumResponse) GetProduct() float64 {
	if x != nil {
		return x.Product
	}
	return 0
}

// CheckStatusRequest has boolean parameters
type CheckStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsActive         bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	SendNotification bool                   `protobuf:"varint,2,opt,name=send_notification,json=sendNotification,proto3" json:"send_notification,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckStatusRequest) Reset() {
	*x = CheckStatusRequest{}
	mi := &file_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusRequest) ProtoMessage() {}

func (x *CheckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckStatusRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{4}
}

func (x *CheckStatusRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CheckStatusRequest) GetSendNotification() bool {
	if x != nil {
		return x.SendNotification
	}
	return false
}

// CheckStatusResponse returns boolean and string results
type CheckStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusResponse) Reset() {
	*x = CheckStatusResponse{}
	mi := &file_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusResponse) ProtoMessage() {}

func (x *CheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{5}
}

func (x *CheckStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ProcessNamesRequest has array parameters
type ProcessNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Counts        []int32                `protobuf:"varint,2,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessNamesRequest) Reset() {
	*x = ProcessNamesRequest{}
	mi := &file_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessNamesRequest) ProtoMessage() {}

func (x *ProcessNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessNamesRequest.ProtoReflect.Descriptor instead.
func (*ProcessNamesRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessNamesRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *ProcessNamesRequest) GetCounts() []int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

// ProcessNamesResponse returns arrays
type ProcessNamesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProcessedNames  []string               `protobuf:"bytes,1,rep,name=processed_names,json=processedNames,proto3" json:"processed_names,omitempty"`
	ProcessedCounts []int32                `protobuf:"varint,2,rep,packed,name=processed_counts,json=processedCounts,proto3" json:"processed_counts,omitempty"`
	Summary         string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessNamesResponse) Reset() {
	*x = ProcessNamesResponse{}
	mi := &file_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessNamesResponse) ProtoMessage() {}

func (x *ProcessNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessNamesResponse.ProtoReflect.Descriptor instead.
func (*ProcessNamesResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessNamesResponse) GetProcessedNames() []string {
	if x != nil {
		return x.ProcessedNames
	}
	return nil
}

func (x *ProcessNamesResponse) GetProcessedCounts() []int32 {
	if x != nil {
		return x.ProcessedCounts
	}
	return nil
}

func (x *ProcessNamesResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// ComplexOperationRequest demonstrates mixed types
type ComplexOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationName string                 `protobuf:"bytes,1,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	IsPriority    bool                   `protobuf:"varint,2,opt,name=is_priority,json=isPriority,proto3" json:"is_priority,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Values        []float64              `protobuf:"fixed64,5,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexOperationRequest) Reset() {
	*x = ComplexOperationRequest{}
	mi := &file_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexOperationRequest) ProtoMessage() {}

func (x *ComplexOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexOperationRequest.ProtoReflect.Descriptor instead.
func (*ComplexOperationRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{8}
}

func (x *ComplexOperationRequest) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *ComplexOperationRequest) GetIsPriority() bool {
	if x != nil {
		return x.IsPriority
	}
	return false
}

func (x *ComplexOperationRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ComplexOperationRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ComplexOperationRequest) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

// ComplexOperationResponse demonstrates mixed return types
type ComplexOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Results       []string               `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	Average       float64                `protobuf:"fixed64,5,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexOperationResponse) Reset() {
	*x = ComplexOperationResponse{}
	mi := &file_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexOperationResponse) ProtoMessage() {}

func (x *ComplexOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexOperationResponse.ProtoReflect.Descriptor instead.
func (*ComplexOperationResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{9}
}

func (x *ComplexOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ComplexOperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ComplexOperationResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ComplexOperationResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ComplexOperationResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

// Request and response messages for Tool1
type Tool1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool1Request) Reset() {
	*x = Tool1Request{}
	mi := &file_example_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool1Request) ProtoMessage() {}

func (x *Tool1Request) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool1Request.ProtoReflect.Descriptor instead.
func (*Tool1Request) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{10}
}

func (x *Tool1Request) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Tool1Request) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

type Tool1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool1Response) Reset() {
	*x = Tool1Response{}
	mi := &file_example_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool1Response) ProtoMessage() {}

func (x *Tool1Response) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool1Response.ProtoReflect.Descriptor instead.
func (*Tool1Response) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{11}
}

func (x *Tool1Response) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

// Request and response messages for Tool2
type Tool2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool2Request) Reset() {
	*x = Tool2Request{}
	mi := &file_example_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool2Request) ProtoMessage() {}

func (x *Tool2Request) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool2Request.ProtoReflect.Descriptor instead.
func (*Tool2Request) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{12}
}

func (x *Tool2Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Tool2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool2Response) Reset() {
	*x = Tool2Response{}
	mi := &file_example_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool2Response) ProtoMessage() {}

func (x *Tool2Response) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool2Response.ProtoReflect.Descriptor instead.
func (*Tool2Response) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{13}
}

func (x *Tool2Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Tool3Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WallaceFavoriteFood string                 `protobuf:"bytes,1,opt,name=wallace_favorite_food,json=wallaceFavoriteFood,proto3" json:"wallace_favorite_food,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Tool3Request) Reset() {
	*x = Tool3Request{}
	mi := &file_example_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool3Request) ProtoMessage() {}

func (x *Tool3Request) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool3Request.ProtoReflect.Descriptor instead.
func (*Tool3Request) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{14}
}

func (x *Tool3Request) GetWallaceFavoriteFood() string {
	if x != nil {
		return x.WallaceFavoriteFood
	}
	return ""
}

type Tool3Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HisFavoriteFood string                 `protobuf:"bytes,1,opt,name=his_favorite_food,json=hisFavoriteFood,proto3" json:"his_favorite_food,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Tool3Response) Reset() {
	*x = Tool3Response{}
	mi := &file_example_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool3Response) ProtoMessage() {}

func (x *Tool3Response) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool3Response.ProtoReflect.Descriptor instead.
func (*Tool3Response) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{15}
}

func (x *Tool3Response) GetHisFavoriteFood() string {
	if x != nil {
		return x.HisFavoriteFood
	}
	return ""
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x12\aexample\"P\n" +
	"\x12GreetPersonRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\"1\n" +
	"\x13GreetPersonResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"a\n" +
	"\x13CalculateSumRequest\x12\x18\n" +
	"\anumber1\x18\x01 \x01(\x05R\anumber1\x12\x18\n" +
	"\anumber2\x18\x02 \x01(\x05R\anumber2\x12\x16\n" +
	"\x06factor\x18\x03 \x01(\x01R\x06factor\"B\n" +
	"\x14CalculateSumResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x05R\x03sum\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\x01R\aproduct\"^\n" +
	"\x12CheckStatusRequest\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12+\n" +
	"\x11send_notification\x18\x02 \x01(\bR\x10sendNotification\"I\n" +
	"\x13CheckStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x13ProcessNamesRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12\x16\n" +
	"\x06counts\x18\x02 \x03(\x05R\x06counts\"\x84\x01\n" +
	"\x14ProcessNamesResponse\x12'\n" +
	"\x0fprocessed_names\x18\x01 \x03(\tR\x0eprocessedNames\x12)\n" +
	"\x10processed_counts\x18\x02 \x03(\x05R\x0fprocessedCounts\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"\xa7\x01\n" +
	"\x17ComplexOperationRequest\x12%\n" +
	"\x0eoperation_name\x18\x01 \x01(\tR\roperationName\x12\x1f\n" +
	"\vis_priority\x18\x02 \x01(\bR\n" +
	"isPriority\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x12\x16\n" +
	"\x06values\x18\x05 \x03(\x01R\x06values\"\xac\x01\n" +
	"\x18ComplexOperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\aresults\x18\x04 \x03(\tR\aresults\x12\x18\n" +
	"\aaverage\x18\x05 \x01(\x01R\aaverage\"H\n" +
	"\fTool1Request\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\"+\n" +
	"\rTool1Response\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\"\"\n" +
	"\fTool2Request\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\rTool2Response\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"B\n" +
	"\fTool3Request\x122\n" +
	"\x15wallace_favorite_food\x18\x01 \x01(\tR\x13wallaceFavoriteFood\";\n" +
	"\rTool3Response\x12*\n" +
	"\x11his_favorite_food\x18\x01 \x01(\tR\x0fhisFavoriteFood2\x97\x03\n" +
	"\x0eExampleService\x12H\n" +
	"\vGreetPerson\x12\x1b.example.GreetPersonRequest\x1a\x1c.example.GreetPersonResponse\x12K\n" +
	"\fCalculateSum\x12\x1c.example.CalculateSumRequest\x1a\x1d.example.CalculateSumResponse\x12H\n" +
	"\vCheckStatus\x12\x1b.example.CheckStatusRequest\x1a\x1c.example.CheckStatusResponse\x12K\n" +
	"\fProcessNames\x12\x1c.example.ProcessNamesRequest\x1a\x1d.example.ProcessNamesResponse\x12W\n" +
	"\x10ComplexOperation\x12 .example.ComplexOperationRequest\x1a!.example.ComplexOperationResponse2\xb1\x01\n" +
	"\aMyTools\x126\n" +
	"\x05Tool1\x12\x15.example.Tool1Request\x1a\x16.example.Tool1Response\x126\n" +
	"\x05Tool2\x12\x15.example.Tool2Request\x1a\x16.example.Tool2Response\x126\n" +
	"\x05Tool3\x12\x15.example.Tool3Request\x1a\x16.example.Tool3ResponseB\x89\x01\n" +
	"\vcom.exampleB\fExampleProtoP\x01Z0github.com/wricardo/protoc-gen-mcpserver/example\xa2\x02\x03EXX\xaa\x02\aExample\xca\x02\aExample\xe2\x02\x13Example\\GPBMetadata\xea\x02\aExampleb\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_example_proto_goTypes = []any{
	(*GreetPersonRequest)(nil),       // 0: example.GreetPersonRequest
	(*GreetPersonResponse)(nil),      // 1: example.GreetPersonResponse
	(*CalculateSumRequest)(nil),      // 2: example.CalculateSumRequest
	(*CalculateSumResponse)(nil),     // 3: example.CalculateSumResponse
	(*CheckStatusRequest)(nil),       // 4: example.CheckStatusRequest
	(*CheckStatusResponse)(nil),      // 5: example.CheckStatusResponse
	(*ProcessNamesRequest)(nil),      // 6: example.ProcessNamesRequest
	(*ProcessNamesResponse)(nil),     // 7: example.ProcessNamesResponse
	(*ComplexOperationRequest)(nil),  // 8: example.ComplexOperationRequest
	(*ComplexOperationResponse)(nil), // 9: example.ComplexOperationResponse
	(*Tool1Request)(nil),             // 10: example.Tool1Request
	(*Tool1Response)(nil),            // 11: example.Tool1Response
	(*Tool2Request)(nil),             // 12: example.Tool2Request
	(*Tool2Response)(nil),            // 13: example.Tool2Response
	(*Tool3Request)(nil),             // 14: example.Tool3Request
	(*Tool3Response)(nil),            // 15: example.Tool3Response
}
var file_example_proto_depIdxs = []int32{
	0,  // 0: example.ExampleService.GreetPerson:input_type -> example.GreetPersonRequest
	2,  // 1: example.ExampleService.CalculateSum:input_type -> example.CalculateSumRequest
	4,  // 2: example.ExampleService.CheckStatus:input_type -> example.CheckStatusRequest
	6,  // 3: example.ExampleService.ProcessNames:input_type -> example.ProcessNamesRequest
	8,  // 4: example.ExampleService.ComplexOperation:input_type -> example.ComplexOperationRequest
	10, // 5: example.MyTools.Tool1:input_type -> example.Tool1Request
	12, // 6: example.MyTools.Tool2:input_type -> example.Tool2Request
	14, // 7: example.MyTools.Tool3:input_type -> example.Tool3Request
	1,  // 8: example.ExampleService.GreetPerson:output_type -> example.GreetPersonResponse
	3,  // 9: example.ExampleService.CalculateSum:output_type -> example.CalculateSumResponse
	5,  // 10: example.ExampleService.CheckStatus:output_type -> example.CheckStatusResponse
	7,  // 11: example.ExampleService.ProcessNames:output_type -> example.ProcessNamesResponse
	9,  // 12: example.ExampleService.ComplexOperation:output_type -> example.ComplexOperationResponse
	11, // 13: example.MyTools.Tool1:output_type -> example.Tool1Response
	13, // 14: example.MyTools.Tool2:output_type -> example.Tool2Response
	15, // 15: example.MyTools.Tool3:output_type -> example.Tool3Response
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
