// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: mytools.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request and response messages for Tool1
type Tool1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
}

func (x *Tool1Request) Reset() {
	*x = Tool1Request{}
	mi := &file_mytools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool1Request) ProtoMessage() {}

func (x *Tool1Request) ProtoReflect() protoreflect.Message {
	mi := &file_mytools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool1Request.ProtoReflect.Descriptor instead.
func (*Tool1Request) Descriptor() ([]byte, []int) {
	return file_mytools_proto_rawDescGZIP(), []int{0}
}

func (x *Tool1Request) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Tool1Request) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

type Tool1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fullname string `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
}

func (x *Tool1Response) Reset() {
	*x = Tool1Response{}
	mi := &file_mytools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool1Response) ProtoMessage() {}

func (x *Tool1Response) ProtoReflect() protoreflect.Message {
	mi := &file_mytools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool1Response.ProtoReflect.Descriptor instead.
func (*Tool1Response) Descriptor() ([]byte, []int) {
	return file_mytools_proto_rawDescGZIP(), []int{1}
}

func (x *Tool1Response) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

// Request and response messages for Tool2
type Tool2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Tool2Request) Reset() {
	*x = Tool2Request{}
	mi := &file_mytools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool2Request) ProtoMessage() {}

func (x *Tool2Request) ProtoReflect() protoreflect.Message {
	mi := &file_mytools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool2Request.ProtoReflect.Descriptor instead.
func (*Tool2Request) Descriptor() ([]byte, []int) {
	return file_mytools_proto_rawDescGZIP(), []int{2}
}

func (x *Tool2Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Tool2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Tool2Response) Reset() {
	*x = Tool2Response{}
	mi := &file_mytools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool2Response) ProtoMessage() {}

func (x *Tool2Response) ProtoReflect() protoreflect.Message {
	mi := &file_mytools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool2Response.ProtoReflect.Descriptor instead.
func (*Tool2Response) Descriptor() ([]byte, []int) {
	return file_mytools_proto_rawDescGZIP(), []int{3}
}

func (x *Tool2Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Tool3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WallaceFavoriteFood string `protobuf:"bytes,1,opt,name=wallace_favorite_food,json=wallaceFavoriteFood,proto3" json:"wallace_favorite_food,omitempty"`
}

func (x *Tool3Request) Reset() {
	*x = Tool3Request{}
	mi := &file_mytools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool3Request) ProtoMessage() {}

func (x *Tool3Request) ProtoReflect() protoreflect.Message {
	mi := &file_mytools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool3Request.ProtoReflect.Descriptor instead.
func (*Tool3Request) Descriptor() ([]byte, []int) {
	return file_mytools_proto_rawDescGZIP(), []int{4}
}

func (x *Tool3Request) GetWallaceFavoriteFood() string {
	if x != nil {
		return x.WallaceFavoriteFood
	}
	return ""
}

type Tool3Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HisFavoriteFood string `protobuf:"bytes,1,opt,name=his_favorite_food,json=hisFavoriteFood,proto3" json:"his_favorite_food,omitempty"`
}

func (x *Tool3Response) Reset() {
	*x = Tool3Response{}
	mi := &file_mytools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool3Response) ProtoMessage() {}

func (x *Tool3Response) ProtoReflect() protoreflect.Message {
	mi := &file_mytools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool3Response.ProtoReflect.Descriptor instead.
func (*Tool3Response) Descriptor() ([]byte, []int) {
	return file_mytools_proto_rawDescGZIP(), []int{5}
}

func (x *Tool3Response) GetHisFavoriteFood() string {
	if x != nil {
		return x.HisFavoriteFood
	}
	return ""
}

var File_mytools_proto protoreflect.FileDescriptor

var file_mytools_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x79, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x48, 0x0a, 0x0c, 0x54, 0x6f,
	0x6f, 0x6c, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x0d, 0x54, 0x6f, 0x6f, 0x6c, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x6f, 0x6c, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x54, 0x6f, 0x6f, 0x6c, 0x32, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x42,
	0x0a, 0x0c, 0x54, 0x6f, 0x6f, 0x6c, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32,
	0x0a, 0x15, 0x77, 0x61, 0x6c, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x5f, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x77,
	0x61, 0x6c, 0x6c, 0x61, 0x63, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x46, 0x6f,
	0x6f, 0x64, 0x22, 0x3b, 0x0a, 0x0d, 0x54, 0x6f, 0x6f, 0x6c, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x68, 0x69, 0x73, 0x5f, 0x66, 0x61, 0x76, 0x6f, 0x72,
	0x69, 0x74, 0x65, 0x5f, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x68, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x32,
	0xbd, 0x01, 0x0a, 0x07, 0x4d, 0x79, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x3a, 0x0a, 0x05, 0x54,
	0x6f, 0x6f, 0x6c, 0x31, 0x12, 0x17, 0x2e, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67,
	0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x31, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x54, 0x6f, 0x6f, 0x6c, 0x32,
	0x12, 0x17, 0x2e, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x6f, 0x6f,
	0x6c, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x6f, 0x6d, 0x65,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x54, 0x6f, 0x6f, 0x6c, 0x33, 0x12, 0x17, 0x2e, 0x73,
	0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x33, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x7c, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67,
	0x42, 0x0c, 0x4d, 0x79, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x19, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x3b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0xa2, 0x02, 0x03, 0x53, 0x58,
	0x58, 0xaa, 0x02, 0x09, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0xca, 0x02, 0x09,
	0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0xe2, 0x02, 0x15, 0x53, 0x6f, 0x6d, 0x65,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x09, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mytools_proto_rawDescOnce sync.Once
	file_mytools_proto_rawDescData = file_mytools_proto_rawDesc
)

func file_mytools_proto_rawDescGZIP() []byte {
	file_mytools_proto_rawDescOnce.Do(func() {
		file_mytools_proto_rawDescData = protoimpl.X.CompressGZIP(file_mytools_proto_rawDescData)
	})
	return file_mytools_proto_rawDescData
}

var file_mytools_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mytools_proto_goTypes = []any{
	(*Tool1Request)(nil),  // 0: something.Tool1Request
	(*Tool1Response)(nil), // 1: something.Tool1Response
	(*Tool2Request)(nil),  // 2: something.Tool2Request
	(*Tool2Response)(nil), // 3: something.Tool2Response
	(*Tool3Request)(nil),  // 4: something.Tool3Request
	(*Tool3Response)(nil), // 5: something.Tool3Response
}
var file_mytools_proto_depIdxs = []int32{
	0, // 0: something.MyTools.Tool1:input_type -> something.Tool1Request
	2, // 1: something.MyTools.Tool2:input_type -> something.Tool2Request
	4, // 2: something.MyTools.Tool3:input_type -> something.Tool3Request
	1, // 3: something.MyTools.Tool1:output_type -> something.Tool1Response
	3, // 4: something.MyTools.Tool2:output_type -> something.Tool2Response
	5, // 5: something.MyTools.Tool3:output_type -> something.Tool3Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mytools_proto_init() }
func file_mytools_proto_init() {
	if File_mytools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mytools_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mytools_proto_goTypes,
		DependencyIndexes: file_mytools_proto_depIdxs,
		MessageInfos:      file_mytools_proto_msgTypes,
	}.Build()
	File_mytools_proto = out.File
	file_mytools_proto_rawDesc = nil
	file_mytools_proto_goTypes = nil
	file_mytools_proto_depIdxs = nil
}
